<a href="https://colab.research.google.com/github/ItoroKoffi/Pytorch-Deep-Learning/blob/main/Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [99]:
#check GPU
!nvidia-smi

Sun Aug 17 20:55:58 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   42C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [100]:
#import required libraries
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__) # checks pytorch version


2.6.0+cu124


##Introduction to Tensors

###Creating tensors

Pytorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [101]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [102]:
scalar.ndim # check dimensions

0

In [103]:
#Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [104]:
vector.ndim

1

In [105]:
#matrix
matrix=torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [106]:
matrix.ndim

2

In [107]:
matrix.shape

torch.Size([2, 2])

In [108]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                    [3,6,9],
                    [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [109]:
TENSOR.ndim

3

In [110]:
TENSOR.shape

torch.Size([1, 3, 3])

In [111]:
a=torch.tensor([[[1],[2]],[[1],[1]],[[1],[2]]]) #practice
a

tensor([[[1],
         [2]],

        [[1],
         [1]],

        [[1],
         [2]]])

In [112]:
a.shape

torch.Size([3, 2, 1])

### Random Tensors
Why random tensors?

Random tensors are important because the way nn learns is that they start with random numbers, and then adjust those numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [113]:
#create a random tensor of shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9954, 0.8730, 0.2810, 0.3577],
        [0.0831, 0.6033, 0.4939, 0.5869],
        [0.1222, 0.7699, 0.9229, 0.3515]])

In [114]:
random_tensor.ndim

2

In [115]:
#create  a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3)) #height, width, color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

###Zeros and Ones

In [116]:
#create a tensor of all zeros
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [117]:
#create a tensor of ones
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [118]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [119]:
# use torch.range()
one_to_ten= torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
#steps
x= torch.arange(start=0,end=11, step=1)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [121]:
#creating tensors like
#creates zeros with same shape as one_to_ten
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor Datatype is one of the 3 big errors you'll run into with PyTorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [122]:
#Float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0], dtype=None,)
float_32_tensor

tensor([3., 6., 9.])

In [123]:
float_32_tensor.dtype
#by default, tensor dtype is float32 (single precision)

torch.float32

In [124]:
float_16_tensor=torch.tensor([3.0,6.0,9.0], dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [125]:
float_16_tensor.dtype

torch.float16

In [126]:
#Float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None, # what datatype is the tensor (e,g float32 or float16)
                             device=None, #what device is your tensor on
                             requires_grad=False #whether or not to track gradients with this tensor operation
                             )
float_32_tensor

tensor([3., 6., 9.])

In [127]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [128]:
#multiply two tensors
x=float_16_tensor*float_32_tensor

In [129]:
x.dtype

torch.float32

### Getting information from Tensors (tensor attributes)
1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [130]:
#create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.0946, 0.9280, 0.5854, 0.6172],
        [0.8881, 0.6485, 0.2352, 0.8697],
        [0.1882, 0.7166, 0.1209, 0.5642]])

In [131]:
#find out details about soem tensor
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device tensor is on : {some_tensor.device}")

tensor([[0.0946, 0.9280, 0.5854, 0.6172],
        [0.8881, 0.6485, 0.2352, 0.8697],
        [0.1882, 0.7166, 0.1209, 0.5642]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([3, 4])
Device tensor is on : cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [132]:
##create a tensor and add 10 to it
tensor= torch.tensor([1,2,3])
tensor+100

tensor([101, 102, 103])

In [133]:
#multiply tensor by 10
tensor*10

tensor([10, 20, 30])

In [134]:
#subtract 10
tensor-10

tensor([-9, -8, -7])

In [135]:
#Tryout Pytorch in-bulit functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [136]:
torch.add(tensor,10)

tensor([11, 12, 13])

###Matrix Multiplication

Two main ways of performing multiplication in nn & deep learning

1. element-wise multiplication
2. matirx multiplication

Two main rules must be satisfied when performing matrix multiplication
1. The *inner dimensions** must match
* `(3, 2) @ (3, 2) ` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` wil work

2. The resulting matrix has shape of **outer dimension**
 * `(2, 3) * (3, 2) -> (2, 2)`
 * `(3, 2) * (2, 3) -> (3, 3)`

In [137]:
#element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [138]:
#Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [139]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.1315, 0.2203, 0.1512],
        [0.3638, 0.3520, 0.2960],
        [0.6670, 0.4756, 0.4620]])

### One of the most common errors in DL: Shape errors


In [140]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
torch.mm(tensor_A,tensor_B) #torch.mm is the same as torch.matmul (it's an alias for matmul)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [141]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

To fix out tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor


In [142]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [143]:
#The matrix multiplication works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum etc ( tensor aggregation)

In [144]:
#create a tensor
x=torch.arange(0,100,10)
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [145]:
#find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [146]:
#find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [147]:
#find the mean
#note this wont work on dtype = torch.float64
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [148]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the Positional min and max

In [149]:
#finds the postion in tensor that has minimum value and returns the index position
x.argmin()

tensor(0)

In [150]:
#finds the postion in tensor that has maximum value and returns the index position
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezign tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [151]:
#create tensor
x= torch.arange(1.,10,)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [152]:
# Add an extra dimension
x_reshaped = x.reshape (1, 9) # the new shape must be compatible with original size
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [153]:
# Change of view

z=x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [154]:
#view shares mermory with original tensor, changing z changes x
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [155]:
#stack tensors on top of each other
x_stacked = torch.stack ([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [156]:
#torch.squeeze
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [157]:
x_reshaped.squeeze().shape

torch.Size([9])

In [158]:
print(f"previous tensor: {x_reshaped}")
print(f"Precious shaape: {x_reshaped.shape}")

#remove extra dimensions from x_reshaped
x_squeezed=x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shaoe: {x_squeezed.shape}")

previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Precious shaape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shaoe: torch.Size([9])


In [159]:
#torch.unsqueeze() adds a single dim to a target tensor at a specific dim
print(f"previous target: {x_squeezed}")
print(f"Previous shaape: {x_squeezed.shape}")

#add extra dimensions with unsqueeze
x_unsqueezed=x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shaoe: {x_unsqueezed.shape}")

previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shaape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shaoe: torch.Size([1, 9])


In [160]:
#torch.permute rearranges the dimensions of a target tensor in a specified order ( especially used in images)
x_original = torch.rand(size=(224, 224, 3)) #height, width, color channels
#permute the original tensor to rearrange the axis or dim order
x_permuted=x_original.permute(2,0,1) #shifta axis 0 to 1, 1 to 2 and 2 to 0
print(f"Previpus shape: {x_original.shape}")
print(f"New Shape: {x_permuted.shape}") # color channels, height, width

Previpus shape: torch.Size([224, 224, 3])
New Shape: torch.Size([3, 224, 224])


In [161]:
#x_permute shares same mermory as x_original so changing one changes the other
x_original[0,0,0]=728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

### Indexing ( Selecting data from tensors)
indexign with PyTorch is simiilar to indexign with NumPy

In [162]:
#create a tensor
import torch
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [163]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [164]:
x[0][2][2]

tensor(9)

In [165]:
# you can also use ":" to select all of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [166]:
#Get all values of 0th and 1st dimension, but only index 1 of 2nd dimension
x[0,0,1]

tensor(2)

## PyTorch tensors & Numpy

Data in Numpy, want in PyTorch -> `torch.from_numpy(ndarray)`

Data in Pytorch, want in Numpy -> `torch.Tensor.numpy()`

In [167]:
#NumPy array to tensor
#Note: numpy default dtype is float64. Going from numpy to tensor will generate a tensor of float64 datatype
import numpy as np
array =np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [168]:
#change the value of arrray, what will happen to the tensor?
array=array+1
array, tensor
#they don't share memory

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [169]:
#Tensor to numpy array
#Note: tensor default dtype is float32. Going from tensor to numpy will generate a numpy of float32 datatype
tensor=torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [170]:
#change the value of tensor, what will happen to the numpy array?
tensor=tensor+1
numpy_tensor, tensor
# they don't share memory

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2.]))

## Reproducibility (trying to take the random out of random)
how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness.

study:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

In [171]:
#create two random tensors
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.2269, 0.7437, 0.7004, 0.6083],
        [0.6763, 0.4026, 0.6601, 0.4763],
        [0.0764, 0.7852, 0.0210, 0.1746]])
tensor([[0.5089, 0.5672, 0.7317, 0.2923],
        [0.7382, 0.5246, 0.7388, 0.8466],
        [0.3422, 0.1310, 0.9676, 0.9176]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [172]:
#random but rproducible tensors
#set the random seed
random_seed =42
torch.manual_seed(random_seed)

random_tensor_C = torch.rand(3,4)
torch.manual_seed(random_seed)
random_tensor_D = torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)




tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors adn Pytroch objects on GPU and making faster computations
GPU== faster computations on numbers


In [173]:
### 1. Getting a GPU
1. Easiest = Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU. options: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them.

for 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/

SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers (ipython-input-1884354525.py, line 3)

In [174]:
#check for GPU access with PyTorch
torch.cuda.is_available()

True

For pytorch since it's capable of running compute on CPU and GPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

e.g. run on GPU if available, else default to CPU

In [175]:
# setup device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [176]:
#count number of devices
import torch
torch.cuda.device_count()

1

## Putting tensors (and models) on GPU
The reson we want our tensors/models on the GPU is because a GPU results in faster computations


In [177]:
#Create a tensor( default on the CPU)
tensor=torch.tensor([1,2,3])
#tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [178]:
#Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

##Moving tensor back to the CPU

In [179]:
# if tensor is on GPU, you cant transfrom to Numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [180]:
#To fix the GPU tensor with numpy error, we cn first set it to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

##Practice Exercises

Create a random tensor with shape (7, 7).

In [181]:
#import torch
import torch

#create random tensor
random_tensor=torch.rand(size=(7,7))
random_tensor, random_tensor.shape

(tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
         [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
         [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
         [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
         [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
         [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
         [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]]),
 torch.Size([7, 7]))

Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)

In [182]:
# Create another random tensor
random_tensor_B = torch.rand(size=(1,7))

# Perform matrix multiplication
tensor_multiplication =torch.matmul(random_tensor, random_tensor_B.T)
tensor_multiplication

tensor([[1.9625],
        [1.0950],
        [0.9967],
        [1.8910],
        [1.9205],
        [1.0674],
        [1.6949]])

Set the random seed to 0 and do the above over again.

In [183]:
#set random seed
random_seed = 0
torch_manual_seed=torch.manual_seed(random_seed)

#create two random tensors
random_tensor=torch.rand(size=(7,7))
random_tensor_B = torch.rand(size=(1,7))

#multiply random tensors
tensor_multiplication =torch.matmul(random_tensor, random_tensor_B.T)
tensor_multiplication

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent?

If there is, set the GPU random seed to 1234.

In [184]:
# Set random seed on the GPU
GPU_seed = 1234
torch.cuda.manual_seed(seed=GPU_seed)

Create two random tensors of shape (2, 3) and send them both to the GPU. Set torch.manual_seed(1234) when creating the tensors.

In [185]:
# Check for access to GPU
torch.cuda.is_available()


True

In [186]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [187]:
#set random seed
random_seed = 1234
torch_manual_seed=torch.manual_seed(random_seed)
#Create two random tensors on GPU
random_tensor_x=torch.rand(size=(2,3)).to(device)
random_tensor_y=torch.rand(size=(2,3)).to(device)
random_tensor_x, random_tensor_y

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

Perform a matrix multiplication on the tensors you created above

In [188]:
# Perform matmul on tensor_A and tensor_B
tensor_on_gpu_multiplication = torch.matmul(random_tensor_x, random_tensor_y.T)
tensor_on_gpu_multiplication, tensor_on_gpu_multiplication.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

 Find the maximum and minimum values of the output

In [189]:
#Maximum
print(f'Maximum: {torch.max(tensor_on_gpu_multiplication)}')
#Minimum
print(f'Minimum {torch.min(tensor_on_gpu_multiplication)}')

Maximum: 0.5617256760597229
Minimum 0.3647301495075226


Find the maximum and minimum index values of the output

In [190]:
#Maximum Index
print(f'Index where maximum value occurs: {torch.argmax(tensor_on_gpu_multiplication)}')
#Minimum Index
print(f'Index where minimum value occurs: {torch.argmin(tensor_on_gpu_multiplication)}')

Index where maximum value occurs: 3
Index where minimum value occurs: 0


Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [191]:
#set random seed
random_seed = 7
torch_manual_seed=torch.manual_seed(random_seed)
#create random tensor
random_tensor=torch.rand(size=(1,1,1,10))

# Remove single dimensions
random_tensor_squeezed=random_tensor.squeeze()

# Print out tensors and their shapes
print(f'Original tensor: {random_tensor}')
print(f'Squeezed_tensor: {random_tensor_squeezed}')
print(f'\nOriginal tensor shape: {random_tensor.shape}')
print(f'Squeezed tensor shape: {random_tensor_squeezed.shape}')

Original tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Squeezed_tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])

Original tensor shape: torch.Size([1, 1, 1, 10])
Squeezed tensor shape: torch.Size([10])
